# Generated by Django 4.2.11 on 2026-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maasserver", "0343_goodbye_django"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="status_phase",
            field=models.CharField(
                max_length=50,
                null=True,
                blank=True,
                default=None,
                editable=False,
                help_text="Current phase within the main status",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="status_phase_message",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Human-readable description of current phase",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="status_phase_updated",
            field=models.DateTimeField(
                null=True,
                blank=True,
                default=None,
                editable=False,
                help_text="Timestamp when phase was last updated",
            ),
        ),
    ]
